# Generated by Django 5.1.3 on 2024-11-30 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relatorios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelatorioVenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_venda', models.IntegerField(unique=True)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_venda', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ItemVenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto_id', models.IntegerField()),
                ('quantidade', models.IntegerField()),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_venda', to='relatorios.relatoriovenda')),
            ],
        ),
    ]
