# Generated by Django 5.1.3 on 2024-11-30 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relatorios', '0002_relatoriovenda_itemvenda'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.RenameField(
            model_name='itemvenda',
            old_name='venda',
            new_name='relatorio_venda',
        ),
        migrations.RemoveField(
            model_name='itemvenda',
            name='produto_id',
        ),
        migrations.AlterField(
            model_name='relatoriovenda',
            name='id_venda',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='relatoriovenda',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AddField(
            model_name='itemvenda',
            name='produto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='itens_venda', to='relatorios.produto'),
            preserve_default=False,
        ),
    ]
