# Generated by Django 5.1.3 on 2024-11-30 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relatorios', '0003_produto_rename_venda_itemvenda_relatorio_venda_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatorioestoque',
            name='categoria',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='relatorioestoque',
            name='descricao',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='relatorioestoque',
            name='nome',
            field=models.CharField(max_length=100),
        ),
    ]
