# Generated by Django 5.1.3 on 2024-11-30 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relatorios', '0004_alter_relatorioestoque_categoria_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemvenda',
            name='produto',
        ),
        migrations.RenameField(
            model_name='itemvenda',
            old_name='relatorio_venda',
            new_name='venda',
        ),
        migrations.AddField(
            model_name='itemvenda',
            name='produto_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='relatorioestoque',
            name='categoria',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='relatorioestoque',
            name='descricao',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='relatorioestoque',
            name='nome',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='relatoriovenda',
            name='id_venda',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='relatoriovenda',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.DeleteModel(
            name='Produto',
        ),
    ]
